<?php

namespace Pdx\DatasetBundle\Repository;

/**
 * DataSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSetRepository extends \Doctrine\ORM\EntityRepository
{
}
