<?php

namespace Pdx\DatasetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatasetRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DatasetRepository extends EntityRepository
{
    public function findViewableDatasets($sort, $sortDirection )
    {
        $qb = $this->createQueryBuilder('d')
            ->select('d')
            ->where('d.title != :title')
            ->setParameter('title', 'Testset 1611')
            ->orderBy($sort, $sortDirection)
        ;

        return $qb->getQuery()->getResult();
    }
}
