# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    elo.dropbox_client:
#        class: Dropbox\Client
#        arguments:
#            - "%dropbox_token%"
#            - "%dropbox_secret%"

    pdx_csv.handler:
        class: Pdx\Csv\CsvHandler
        arguments: ["@elo_filesystem", ""]

    pdx_csv.geocoder:
        class: Pdx\Csv\GeoCoder
        arguments: ["@pdx_csv.handler", "@pdx.histograph.client"]

    pdx.histograph.client:
        class: Pdx\Histograph\ApiClient
        arguments: ['@logger', '@hg_cache']

    pdx_csv.geojson:
        class: Pdx\Csv\GeoJSONConverter
        arguments: ["@pdx_csv.handler"]

#    app.form.dataset_map:
#        class: Pdx\DatasetBundle\Form\DataSetMapType
#        arguments: ['@pdx_csv.handler']
#        tags:
#            - { name: form.type }
